# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from audio_recorder.protos import audio_server_pb2 as audio__recorder_dot_protos_dot_audio__server__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


class AudioServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StartRecording = channel.unary_unary(
        '/audio_recorder.protos.AudioServer/StartRecording',
        request_serializer=audio__recorder_dot_protos_dot_audio__server__pb2.StartRecordingRequest.SerializeToString,
        response_deserializer=audio__recorder_dot_protos_dot_audio__server__pb2.StartRecordingResponse.FromString,
        )
    self.StopRecording = channel.unary_unary(
        '/audio_recorder.protos.AudioServer/StopRecording',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetStatus = channel.unary_unary(
        '/audio_recorder.protos.AudioServer/GetStatus',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=audio__recorder_dot_protos_dot_audio__server__pb2.Status.FromString,
        )
    self.GetLevels = channel.unary_stream(
        '/audio_recorder.protos.AudioServer/GetLevels',
        request_serializer=audio__recorder_dot_protos_dot_audio__server__pb2.LevelsRequest.SerializeToString,
        response_deserializer=audio__recorder_dot_protos_dot_audio__server__pb2.AudioLevels.FromString,
        )
    self.SetMixer = channel.unary_unary(
        '/audio_recorder.protos.AudioServer/SetMixer',
        request_serializer=audio__recorder_dot_protos_dot_audio__server__pb2.AudioLevels.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetMixer = channel.unary_unary(
        '/audio_recorder.protos.AudioServer/GetMixer',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=audio__recorder_dot_protos_dot_audio__server__pb2.AudioLevels.FromString,
        )
    self.SetTime = channel.unary_unary(
        '/audio_recorder.protos.AudioServer/SetTime',
        request_serializer=google_dot_protobuf_dot_timestamp__pb2.Timestamp.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.StartTimeSync = channel.unary_unary(
        '/audio_recorder.protos.AudioServer/StartTimeSync',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class AudioServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StartRecording(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopRecording(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLevels(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMixer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMixer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartTimeSync(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AudioServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StartRecording': grpc.unary_unary_rpc_method_handler(
          servicer.StartRecording,
          request_deserializer=audio__recorder_dot_protos_dot_audio__server__pb2.StartRecordingRequest.FromString,
          response_serializer=audio__recorder_dot_protos_dot_audio__server__pb2.StartRecordingResponse.SerializeToString,
      ),
      'StopRecording': grpc.unary_unary_rpc_method_handler(
          servicer.StopRecording,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetStatus,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=audio__recorder_dot_protos_dot_audio__server__pb2.Status.SerializeToString,
      ),
      'GetLevels': grpc.unary_stream_rpc_method_handler(
          servicer.GetLevels,
          request_deserializer=audio__recorder_dot_protos_dot_audio__server__pb2.LevelsRequest.FromString,
          response_serializer=audio__recorder_dot_protos_dot_audio__server__pb2.AudioLevels.SerializeToString,
      ),
      'SetMixer': grpc.unary_unary_rpc_method_handler(
          servicer.SetMixer,
          request_deserializer=audio__recorder_dot_protos_dot_audio__server__pb2.AudioLevels.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetMixer': grpc.unary_unary_rpc_method_handler(
          servicer.GetMixer,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=audio__recorder_dot_protos_dot_audio__server__pb2.AudioLevels.SerializeToString,
      ),
      'SetTime': grpc.unary_unary_rpc_method_handler(
          servicer.SetTime,
          request_deserializer=google_dot_protobuf_dot_timestamp__pb2.Timestamp.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'StartTimeSync': grpc.unary_unary_rpc_method_handler(
          servicer.StartTimeSync,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'audio_recorder.protos.AudioServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
